// Global using directives

global using UnmappedAds = u;
global using UnmappedAnims = j;
global using UnmappedBlock = Block;
global using UnmappedBlocks = bz;
global using UnmappedCam = ca;
global using UnmappedController = Controller;
global using UnmappedControls = Controls;
global using UnmappedControls_Switch = k;
global using UnmappedDoor = Door;
global using UnmappedGlobals = l;
global using UnmappedItem = bd;
global using UnmappedItems = be;
global using UnmappedKeyboard = Keyboard;
global using UnmappedMatch = m;
global using UnmappedMenu = o;
global using UnmappedMenus = q;
global using UnmappedMeter = Meter;
global using UnmappedParticle = ba;
global using UnmappedParticles = bb;
global using UnmappedPlayer = Player;
global using UnmappedPlayers = Players;
global using UnmappedPromo = bc;
global using UnmappedSaveSystem = bf;
global using UnmappedSound = Sound;
global using UnmappedSprites = Sprites;
global using UnmappedTab = Tab;
global using UnmappedTaunt = Taunt;
global using UnmappedTextures = by;
global using UnmappedWeapon = Weapon;
global using UnmappedWeapons = Weapons;
global using UnmappedWindow = cd;
global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using System.IO;
global using UnityEngine;
global using ILCCL.Internal;
global using ILCCL.Utils;
global using ILCCL.Managers;
global using ILCCL.API.Types;
global using static ILCCL.Utils.TextureUtils;
global using static ILCCL.Utils.MenuUtils;
global using static ILCCL.Content.CustomContent;
global using static ILCCL.Utils.FileNameUtils;
global using static ILCCL.Utils.ArrayUtils;
global using static ILCCL.Utils.LogUtils;
global using static ILCCL.Utils.ReflectionUtils;